#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \Lxr\Dcf\Commands\SymbolsCommand());
$application->add(new \Lxr\Dcf\Commands\UnusedFilesCommand());
$application->add(new \Lxr\Dcf\Commands\UnusedSymbolsCommand());

$application->run();
